#Default libs catalog

[versions]

# Kotlin
kotlin = "1.7.10"
coroutines = "1.6.4"
kotlinSerialization = "1.3.3"
kotlinDateTime = "0.4.0"

# Compose
composeCompiler = "1.3.0-beta01"

#Hilt
hilt = "2.43.2"
